@api = http://172.22.73.72:5000/api/v1/map/directions

### Get directions google maps
GET  {{api}}
Content-Type: application/json

{
  "origin": "Disneyland",
  "destination": "Universal Studios Hollywood",
  "mode": "",
  "waypoints": "",    
  "avoid": "",
  "departure_time": "",
  "region": "",
  "alternatives": false,
  "arrival_time": "",
  "language": "",
  "optimize": false,
  "units": "",
  "region": "",
  "transit_routing_preference": "",
  "traffic_model": "",
  "transit_mode": ""
}