@api = http://172.21.174.173:5000/api/v1/user

### Get users
GET {{api}}

### Get ser
GET {{api}}/2


### Create user
POST {{api}}
Content-Type: application/json

{
    "username": 123,
    "password": "admin",
    "email": "admin@gmail.com",
    "description": "admin sistem"
}

### Update user
PUT {{api}}/16
Content-Type: application/json

{
 "description": "only admin"
}



### Delete user
DELETE {{api}}/22