@api = http://172.31.98.52:5000/api/v1/user

### Get users
GET {{api}}

### Get ser
GET {{api}}/232


### Create user
POST {{api}}
Content-Type: application/json

{
    "username": 1212,
    "password": "admin",
    "email": "admin@gmail.com",
    "description": "admin sistem"
}

### Update user
PUT {{api}}/23
Content-Type: application/json

{
 "description": "only admin"
}



### Delete user
DELETE {{api}}/40